// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/founders": {
            "get": {
                "description": "Returns total, taken, and available founding creator slots",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "founders"
                ],
                "summary": "Get founding creator slot statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetFoundingCreatorStatsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Submit application to become a founding creator",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "founders"
                ],
                "summary": "Register as founding creator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username (4-14 alphanumeric characters)",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email address",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "URL to dotfiles repository or r/unixporn post",
                        "name": "dotfilesUrl",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "409": {
                        "description": "Username or email already taken",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            }
        },
        "/rices": {
            "get": {
                "description": "Returns a list of all preview rices ordered by creation date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rices"
                ],
                "summary": "Get all preview rices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.GetPreviewRicesResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminSecret": []
                    }
                ],
                "description": "Uploads thumbnail to S3 and stores rice metadata",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rices"
                ],
                "summary": "Create a preview rice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin secret key",
                        "name": "X-Admin-Secret",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rice title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Price (e.g. 15.29, must be \u003e 0)",
                        "name": "price",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Thumbnail image (png, jpeg, webp)",
                        "name": "thumbnail",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Star count",
                        "name": "starCount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Download count",
                        "name": "downloadCount",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Tags",
                        "name": "tags",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "409": {
                        "description": "Title already exists",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            }
        },
        "/waitlist": {
            "get": {
                "description": "Returns total count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "waitlist"
                ],
                "summary": "Get amount of users in waitlist",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetWaitlistEmailCountResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new email address to the waitlist",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "waitlist"
                ],
                "summary": "Add email to waitlist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "409": {
                        "description": "Email already on waitlist",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.APIError": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.GetFoundingCreatorStatsResponse": {
            "type": "object",
            "properties": {
                "slotsAvailable": {
                    "type": "integer"
                },
                "slotsTaken": {
                    "type": "integer"
                },
                "slotsTotal": {
                    "type": "integer"
                }
            }
        },
        "models.GetPreviewRicesResponse": {
            "type": "object",
            "properties": {
                "downloadCount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "starCount": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnailUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.GetWaitlistEmailCountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminSecret": {
            "type": "apiKey",
            "name": "X-Admin-Secret",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.6.0",
	Host:             "127.0.0.1:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "RiceHub Waitlist API",
	Description:      "REST API for RiceHub waitlist frontend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
